// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZED1OU8KLlUzZoyuXeHa_cVdQmNVhrkU',
    appId: '1:367014170447:web:ebb393aeb4967edbfebf3a',
    messagingSenderId: '367014170447',
    projectId: 'rudo-1b33e',
    authDomain: 'rudo-1b33e.firebaseapp.com',
    storageBucket: 'rudo-1b33e.firebasestorage.app',
    measurementId: 'G-C47FD37FST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjcUTTdtf1yyRTSzuPXJ6KnPxwYEnVho8',
    appId: '1:367014170447:android:18ee193b4837fb64febf3a',
    messagingSenderId: '367014170447',
    projectId: 'rudo-1b33e',
    storageBucket: 'rudo-1b33e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAor_fvIeNPHm-gKe3vv1lr00qIaH0Tofk',
    appId: '1:367014170447:ios:e180f0e000596233febf3a',
    messagingSenderId: '367014170447',
    projectId: 'rudo-1b33e',
    storageBucket: 'rudo-1b33e.firebasestorage.app',
    androidClientId: '367014170447-joogeoc8mue3iktvo3ceu19gsm72r5hk.apps.googleusercontent.com',
    iosClientId: '367014170447-h30ae00mbtoeit9q63ovsf1tuq38rje1.apps.googleusercontent.com',
    iosBundleId: 'com.example.stream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAor_fvIeNPHm-gKe3vv1lr00qIaH0Tofk',
    appId: '1:367014170447:ios:e180f0e000596233febf3a',
    messagingSenderId: '367014170447',
    projectId: 'rudo-1b33e',
    storageBucket: 'rudo-1b33e.firebasestorage.app',
    androidClientId: '367014170447-joogeoc8mue3iktvo3ceu19gsm72r5hk.apps.googleusercontent.com',
    iosClientId: '367014170447-h30ae00mbtoeit9q63ovsf1tuq38rje1.apps.googleusercontent.com',
    iosBundleId: 'com.example.stream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZED1OU8KLlUzZoyuXeHa_cVdQmNVhrkU',
    appId: '1:367014170447:web:8658d98ae17b5719febf3a',
    messagingSenderId: '367014170447',
    projectId: 'rudo-1b33e',
    authDomain: 'rudo-1b33e.firebaseapp.com',
    storageBucket: 'rudo-1b33e.firebasestorage.app',
    measurementId: 'G-05GT52ZMPX',
  );

}